development:
  adapter: postgresql
  encoding: utf8
  database: stevegrossi_development
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: utf8
  database: stevegrossi_test
  min_messages: WARNING

staging:
  url: <%= ENV["DATABASE_URL"] %>
production:
  url: <%= ENV["DATABASE_URL"] %>
